CREATE TABLE company (
  NUMBER INTEGER PRIMARY KEY,
  NAME  TEXT ,
  AGE TEXT,
  LOCATION TEXT,
  LEVEL TEXT 
);


  INSERT INTO company VALUES 
  (1, "GABRIEL WALE","25 YEARS","UGANDA","BSC"),
  (2, "ALAUSA OLAWOYIN ","35 YEARS","NIGERIA","SECONDARY SCHOOL"),
  (3, "ODUSANYA JEMEEL ","15 YEARS","QATAR","PHD"),
  (4, "OSENI KHALID ","45 YEARS","CANADA ","MASTERS"),
  (5, "ODUS AZ ","20 YEARS","WAHINGTON DC ","UNDERGRADUATE");
 
  SELECT * FROM company ;


SELECT * FROM company WHERE  AGE ="25" ;
SELECT * FROM company WHERE LEVEL ="UNDERGRADUATE" ;
SELECT * FROM company WHERE LOCATION ="CANADA" ;
SELECT * FROM company WHERE NAME ="GABRIEL WALE" ;